version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./client:/app
      - /app/node_modules

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:@mysql:3306/mediregister
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql
      - redis
    networks:
      - app-network
    volumes:
      - ./server:/app
      - /app/node_modules

  prisma:
    image: prismagraphql/prisma:1.34
    platform: linux/amd64
    restart: always
    ports:
      - '4466:4466'
    depends_on:
      - mysql
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mediregister
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    networks:
      - app-network
    volumes:
      - redis-data:/data

networks:
  app-network:

volumes:
  mysql-data:
  redis-data: